# Site settings
title: "Grimoire"
author: "Saph, thebombzen, Desamir"
description:
  "A searchable D&D 5e spell list."
baseurl: "/grimoire" # the subpath of your site, e.g. /blog/
url: "https://5ecompendium.github.io" # the base hostname & protocol for your site
source-url: "https://github.com/5ecompendium/grimoire/"
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"

collections:
  spells:
    output: true
  tags:
    output: true